Expose wf schedule/execution time
uber/cadence-java-client pull request #333
Opened 2019-07-02 18:05 UTC by meiliang86

Also fix cron first execution time in test framework

2019-07-02 18:06 UTC, meiliang86 commented
#316

2019-07-11 22:15 UTC, mfateev requested changes

2019-07-11 22:15 UTC, mfateev commented on src/main/java/com/uber/cadence/internal/replay/WorkflowContext.java
> +        decisionTask.getHistory().getEvents().get(1).getTimestamp());
I don't think it is always true. For example signalWithStart will have signal as a second event. 
Also when cron workflow is waiting for exectution all received signals will be put before DecisionTaskScheduled.

2026-05-01 17:32 UTC, shijiesheng commented
close ancient PR, but feel free to reopen after rebase if this is still valid

2026-05-01 17:32 UTC, closed without merging