Add support for protobuf in default data converter
uber/cadence-java-client pull request #335
Opened 2019-07-08 21:22 UTC by meiliang86

2019-07-08 21:23 UTC, meiliang86 commented
#294

2019-07-11 22:06 UTC, mfateev requested changes

2019-07-11 22:06 UTC, mfateev commented on src/main/java/com/uber/cadence/converter/JsonDataConverter.java
> +          return protoObj.toByteArray();
I think by default we want to serialize it to JSON to make it UI friendly: https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java

2022-04-07 12:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/cadence-java-client?pullRequest=335) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/cadence-java-client?pullRequest=335) before we can accept your contribution.<br/><hr/>**Liang Mei** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/cadence-java-client?pullRequest=335) it.</sub>

2026-05-01 17:32 UTC, shijiesheng commented
close ancient PR, but feel free to reopen after rebase if this is still valid

2026-05-01 17:32 UTC, closed without merging